(cl:in-package rockauto_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          LABEL-VAL
          LABEL
          SCORE-VAL
          SCORE
          COLOR-VAL
          COLOR
          VALID-VAL
          VALID
          SPACE_FRAME-VAL
          SPACE_FRAME
          POSE-VAL
          POSE
          DIMENSIONS-VAL
          DIMENSIONS
          VARIANCE-VAL
          VARIANCE
          VELOCITY-VAL
          VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          POINTCLOUD-VAL
          POINTCLOUD
          WORLDPOINTCLOUD-VAL
          WORLDPOINTCLOUD
          GRIDMAPPOINT-VAL
          GRIDMAPPOINT
          CONVEX_HULL-VAL
          CONVEX_HULL
          CANDIDATE_TRAJECTORIES-VAL
          CANDIDATE_TRAJECTORIES
          POSE_RELIABLE-VAL
          POSE_RELIABLE
          VELOCITY_RELIABLE-VAL
          VELOCITY_RELIABLE
          ACCELERATION_RELIABLE-VAL
          ACCELERATION_RELIABLE
          IMAGE_FRAME-VAL
          IMAGE_FRAME
          X-VAL
          X
          Y-VAL
          Y
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          ANGLE-VAL
          ANGLE
          ROI_IMAGE-VAL
          ROI_IMAGE
          INDICATOR_STATE-VAL
          INDICATOR_STATE
          BEHAVIOR_STATE-VAL
          BEHAVIOR_STATE
          USER_DEFINED_INFO-VAL
          USER_DEFINED_INFO
          MEAN_POINT-VAL
          MEAN_POINT
          DISTANCE-VAL
          DISTANCE
          WORLD_VELOCITY-VAL
          WORLD_VELOCITY
          LOCAL_VELOCITY-VAL
          LOCAL_VELOCITY
          THETA-VAL
          THETA
          WORLD_POINT-VAL
          WORLD_POINT
          YAW-VAL
          YAW
          YAW_RATE-VAL
          YAW_RATE
))