(cl:in-package rockauto_msgs-msg)
(cl:export '(X_CENTER-VAL
          X_CENTER
          Y_CENTER-VAL
          Y_CENTER
          Z_CENTER-VAL
          Z_CENTER
          GLOBAL_X_CENTER-VAL
          GLOBAL_X_CENTER
          GLOBAL_Y_CENTER-VAL
          GLOBAL_Y_CENTER
          WORLD_THETA-VAL
          WORLD_THETA
          LOCAL_THETA-VAL
          LOCAL_THETA
          WORLD_VELOCITY-VAL
          WORLD_VELOCITY
          LOCAL_VELOCITY-VAL
          LOCAL_VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          CLASSIFICATION-VAL
          CLASSIFICATION
          LOCAL_DIFF_THETA-VAL
          LOCAL_DIFF_THETA
          CONVEX_HULL-VAL
          CONVEX_HULL
          POINTCLOUD-VAL
          POINTCLOUD
          WORLDPOINTCLOUD-VAL
          WORLDPOINTCLOUD
          TRACK_ID-VAL
          TRACK_ID
          PREDICT_X_POSITION-VAL
          PREDICT_X_POSITION
          PREDICT_Y_POSITION-VAL
          PREDICT_Y_POSITION
          PREDICT_WORLD_X_POSITION-VAL
          PREDICT_WORLD_X_POSITION
          PREDICT_WORLD_Y_POSITION-VAL
          PREDICT_WORLD_Y_POSITION
))