// Generated by gencpp from file yolov8_ROS/BoundingBox.msg
// DO NOT EDIT!


#ifndef YOLOV8_ROS_MESSAGE_BOUNDINGBOX_H
#define YOLOV8_ROS_MESSAGE_BOUNDINGBOX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolov8_ROS
{
template <class ContainerAllocator>
struct BoundingBox_
{
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , confidence(0.0)
    , class_label()  {
    }
  BoundingBox_(const ContainerAllocator& _alloc)
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , confidence(0.0)
    , class_label(_alloc)  {
  (void)_alloc;
    }



   typedef float _x1_type;
  _x1_type x1;

   typedef float _y1_type;
  _y1_type y1;

   typedef float _x2_type;
  _x2_type x2;

   typedef float _y2_type;
  _y2_type y2;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_label_type;
  _class_label_type class_label;





  typedef boost::shared_ptr< ::yolov8_ROS::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov8_ROS::BoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox_

typedef ::yolov8_ROS::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::yolov8_ROS::BoundingBox > BoundingBoxPtr;
typedef boost::shared_ptr< ::yolov8_ROS::BoundingBox const> BoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov8_ROS::BoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov8_ROS::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov8_ROS::BoundingBox_<ContainerAllocator1> & lhs, const ::yolov8_ROS::BoundingBox_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2 &&
    lhs.confidence == rhs.confidence &&
    lhs.class_label == rhs.class_label;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov8_ROS::BoundingBox_<ContainerAllocator1> & lhs, const ::yolov8_ROS::BoundingBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov8_ROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov8_ROS::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov8_ROS::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_ROS::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov8_ROS::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_ROS::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov8_ROS::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov8_ROS::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7cb5aadc9e23ac5f2e1ddb4f27e9b5ef";
  }

  static const char* value(const ::yolov8_ROS::BoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7cb5aadc9e23ac5fULL;
  static const uint64_t static_value2 = 0x2e1ddb4f27e9b5efULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov8_ROS::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov8_ROS/BoundingBox";
  }

  static const char* value(const ::yolov8_ROS::BoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov8_ROS::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x1\n"
"float32 y1\n"
"float32 x2\n"
"float32 y2\n"
"float32 confidence\n"
"string class_label\n"
;
  }

  static const char* value(const ::yolov8_ROS::BoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov8_ROS::BoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.confidence);
      stream.next(m.class_label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov8_ROS::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov8_ROS::BoundingBox_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<float>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<float>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<float>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<float>::stream(s, indent + "  ", v.y2);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "class_label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV8_ROS_MESSAGE_BOUNDINGBOX_H
